name: Deploy Montreal Market
on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'  # Changed to stable Node.js 20 LTS
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        
      - name: Deploy to Droplet
        uses: appleboy/scp-action@v0.1.7  # Specified version explicitly
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/montreal-market"
          strip_components: 1
          
      - name: Post-deploy commands
        uses: appleboy/ssh-action@v1.0.3  # Updated to latest version
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl restart nginx